version: '3'

services: 
  ldap:
    image: toolscloud/ldap:v18.0
    volumes:
      - /var/lib/ldap
      - /usr/local/var/openldap-data
    networks:
      - general
  
  postgresql:
    image: toolscloud/postgresql:v18.0
    volumes: 
      - /var/lib/postgresql
      - /run/postgresql
    networks:
      - general

  pla: 
    image: toolscloud/phpldapadmin:v18.0
    networks:
      - general
  
  git:
    image: toolscloud/gitblit:v18.0
    ports: 
      - "9418:9418"
      - "29418:29418"
      # - "8085:8085"
      # - "8447:8447"
    volumes: 
      - /opt/gitblit-data
    networks:
      - general
  
  nexus:
    image: toolscloud/sonatype-nexus:v18.0
    # ports: 
    #   - "8080:8081"
    volumes: 
      - /opt/sonatype-work
    networks:
      - general
  
  redmine:
    image: toolscloud/redmine:v18.0
    # ports:
    #   - "8444:8444"
    networks:
      - general
    environment: 
      - DB_TYPE=postgres
      - DB_NAME=redmine_production 
      - DB_USER=redmine
      - DB_PASS=!AdewhmOP@12
    volumes:
      - /home/redmine/data
      - /var/log/redmine
  
  jenkins:
    image: toolscloud/jenkins:v18.0.1
    ports:
      - "50000:50000"
    user: root 
    volumes:
      - /var/jenkins_home
      - /root/.m2
    networks:
      - general
  
  sonar:
    image: toolscloud/sonar-server:v18.0
    environment:  
      - DBMS=postgresql
    volumes: 
      - /opt/sonar/extensions
      - /opt/sonar/data
    networks:
      - general
  
  testlink:
    image: toolscloud/testlink:v18.0.1
    # ports: 
    #   - "8082:80"
    volumes:
      - /var/testlink/upload_area
      - /var/testlink/logs
    networks:
      - general
  
  manager:
    image: toolscloud/manager:v18.0
    volumes:
      - /var/log/apache2
      - /etc/ssl/certs
      - /etc/ssl/private
    ports: 
      - "8000:80"
      - "4443:443"
    networks:
      - general

# volumes:
#   data:

networks:
  general:
